version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - PORT=5000
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app:/app/src
    command: flask run --host=0.0.0.0 --port=5000
